--vim.g.tokyonight_transparent_sidebar = true
--vim.g.tokyonight_transparent = true
--vim.g.tokyonight_style = "dark"
--vim.cmd("colorscheme tokyonight")
--vim.cmd("hi EndOfBuffer guibg=NONE ctermbg=NONE")
--vim.cmd("hi Normal guibg=NONE ctermbg=NONE")
--vim.cmd("hi NormalFloat guibg=NONE ctermbg=NONE")
--vim.cmd("hi! link NormalFloat Normal")
